### ISSUE TITLE
Pressing back button skips a screen

### ISSUE THREAD

**Issue by sachdeva-shrey** [srm-kzilla/violet-air#11]
## Description
Pressing the back button on the `CityScreen` takes back to the `HomeScreen`. It should take the user back to the `MapView`.

## Screenshot
![WhatsApp Image 2020-10-02 at 7 00 02 PM](https://user-images.githubusercontent.com/47667325/94928625-9b06d100-04e1-11eb-9cd0-11d4574562a2.jpeg)

**Comment by kala2** [comment]
Hello, May i please?

**Comment by varshaig1999** [comment]
hello @sachdeva-shrey  can you please assign this to me?

**Comment by sachdeva-shrey** [comment]
Hey @kala2! I'll assign this on to you since you asked first. 
I'm sorry, @varshaig1999, we have a lot of issues open on our other repositories too which you might want to take up!

**Comment by ericvicenti** [comment]
One way of accomplishing this is by using the drawer navigator from React
Navigation. This navigator will handle the back button and will also give
us a handy drawer/sidebar in the city screen.

https://reactnavigation.org/docs/drawer-based-navigation/

Or this can be done by overriding the back button:

https://reactnavigation.org/docs/custom-android-back-button-handling/

**Comment by saa27** [comment]
Hey @sachdeva-shrey ! I would like to work on this. Can you assign it to me please?

**Comment by sachdeva-shrey** [comment]
Hey @saa27! Sure, it's all yours! :)
